# Generated by Django 5.1.3 on 2024-11-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='status_reserva',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
