# Generated by Django 5.1.3 on 2024-11-30 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_status_reserva_reserva_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='recursos',
            new_name='recursos_disponiveis',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='status',
        ),
        migrations.AddField(
            model_name='reserva',
            name='status_reserva',
            field=models.CharField(choices=[('C', 'Confirmada'), ('P', 'Pendente')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sala',
            name='status',
            field=models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa')], max_length=1),
        ),
    ]
