# Generated by Django 5.1.3 on 2024-11-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_rename_recursos_sala_recursos_disponiveis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='horarios_disponiveis',
            field=models.JSONField(default=list),
        ),
    ]
