# Generated by Django 5.1.3 on 2024-11-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_sala_horarios_disponiveis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='horarios_disponiveis',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
