# Generated by Django 5.1.3 on 2024-11-30 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_sala_horarios_disponiveis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='horarios_disponiveis',
        ),
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponiveis', to='reservas.sala')),
            ],
        ),
    ]
